name: Scrape-Daily

on:
  push:
    branches: 
      - 'master'
  schedule: 
    # Runs every day at 5 p.m. EST
    - cron: '0 21 * * *'

jobs:
  build:
    name: Do stuff
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Scrape Webpage
        run: |
          python scrape.py
    
